// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeAI2dSuD8UpOFoya0_xvVGKcZc82E9aw',
    appId: '1:188583481538:android:6675c674688b8e23fa2b5b',
    messagingSenderId: '188583481538',
    projectId: 'fir-todo-3dc3c',
    storageBucket: 'fir-todo-3dc3c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkIOrieCjzRelXTW54WSQ6iJYeftoodo',
    appId: '1:188583481538:web:2a53f8069e6d62f9fa2b5b',
    messagingSenderId: '188583481538',
    projectId: 'fir-todo-3dc3c',
    authDomain: 'fir-todo-3dc3c.firebaseapp.com',
    storageBucket: 'fir-todo-3dc3c.firebasestorage.app',
    measurementId: 'G-HXFT7Q3QG0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcLYZVpUSC7HaCSWGP28_EgUm9YvlFTkE',
    appId: '1:188583481538:ios:08b6ae7b1709b466fa2b5b',
    messagingSenderId: '188583481538',
    projectId: 'fir-todo-3dc3c',
    storageBucket: 'fir-todo-3dc3c.firebasestorage.app',
    androidClientId: '188583481538-4msoiih8cnai8qe8l3cui629i2r171l1.apps.googleusercontent.com',
    iosClientId: '188583481538-p0hf2g04djha3f5drjqkis9segleo9f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcLYZVpUSC7HaCSWGP28_EgUm9YvlFTkE',
    appId: '1:188583481538:ios:08b6ae7b1709b466fa2b5b',
    messagingSenderId: '188583481538',
    projectId: 'fir-todo-3dc3c',
    storageBucket: 'fir-todo-3dc3c.firebasestorage.app',
    androidClientId: '188583481538-4msoiih8cnai8qe8l3cui629i2r171l1.apps.googleusercontent.com',
    iosClientId: '188583481538-p0hf2g04djha3f5drjqkis9segleo9f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkIOrieCjzRelXTW54WSQ6iJYeftoodo',
    appId: '1:188583481538:web:20abc894cab4c832fa2b5b',
    messagingSenderId: '188583481538',
    projectId: 'fir-todo-3dc3c',
    authDomain: 'fir-todo-3dc3c.firebaseapp.com',
    storageBucket: 'fir-todo-3dc3c.firebasestorage.app',
    measurementId: 'G-Z8L6S3CY12',
  );

}